# Generated by Django 5.1.1 on 2024-09-13 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('LR', 'Low Risk'), ('VR', 'Vulnerable'), ('ED', 'Endangered'), ('CE', 'Critically Endangered')], default='LR', max_length=2)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_zoo_app.animal')),
            ],
        ),
    ]
