# Generated by Django 5.1.1 on 2024-09-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_zoo_app', '0002_conservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doner', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='conservation',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='conservation',
            name='date',
            field=models.DateField(verbose_name='Date Changed'),
        ),
    ]
