# Generated by Django 5.1.1 on 2024-09-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_zoo_app', '0003_donation_alter_conservation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='doner',
            new_name='donor',
        ),
    ]
